(() => {
  "use strict";
  const state = { file:null, phase1:null, phase2:null, busy:false };
  const el = (id) => document.getElementById(id); const fileInput = el("uff-file"); const dropzone = el("dropzone");
  function setMessage(text,type="") { const node=el("message"); node.textContent=text; node.className=`message ${type}`; }
  function setBusy(busy,message="") { state.busy=busy; el("analyze-button").disabled=busy||!state.file; el("phase2-button").disabled=busy||!state.file; if(message)setMessage(message,"loading"); }
  function selectFile(file) { if(!file)return; state.file=file; el("selected-file").textContent=file.name; el("analyze-button").disabled=false; if(!file.name.toLowerCase().endsWith(".uff")){el("analyze-button").disabled=true;setMessage("Please choose a file with the .uff extension.","error");}else setMessage(""); }
  fileInput.addEventListener("change",()=>selectFile(fileInput.files[0])); ["dragenter","dragover"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add("is-dragging");})); ["dragleave","drop"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove("is-dragging");})); dropzone.addEventListener("drop",e=>selectFile(e.dataTransfer.files[0]));
  async function request(endpoint,includeSidebands=false) { const form=new FormData(); form.append("file",state.file); if(endpoint.includes("phase2"))form.append("sideband_analysis",String(includeSidebands)); const response=await fetch(endpoint,{method:"POST",body:form}); let payload; try{payload=await response.json();}catch(_){payload={};} if(!response.ok)throw new Error(payload.error||"The analysis service returned an error."); return payload; }
  function formatNumber(value,digits=2) { if(value===null||value===undefined||value==="")return "—"; return Number(value).toLocaleString(undefined,{maximumFractionDigits:digits}); }
  function renderMetadata(result) { const m=result.metadata; el("file-name").textContent=result.filename; const fields=[["Status","Processed"],["Signal",m.quantity],["Processing",m.processing.replaceAll("_"," ")],["Sample rate",`${formatNumber(m.sample_rate_hz,2)} Hz`],["Samples",formatNumber(m.sample_count,0)],["Unit",result.spectrum.unit]]; el("metadata").innerHTML=fields.map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join(""); el("spectrum-unit").textContent=result.spectrum.unit; }
  function plotLayout(result,phase,annotations={}) { const ref=result.metadata.reference; return { title:{text:phase===1?"Phase 1 · Normal spectrum":"Phase 2 · Detected peaks and characteristic matches",font:{size:15,color:"#152331"},x:.02,xanchor:"left"},margin:{l:72,r:28,t:52,b:58},paper_bgcolor:"#fff",plot_bgcolor:"#fbfcfc",hovermode:"x unified",showlegend:true,legend:{orientation:"h",y:-.18,x:0,font:{size:11}},xaxis:{title:"Frequency [Hz]",range:ref.x_limit,dtick:ref.x_tick,gridcolor:"#dfe7eb",zeroline:false,rangeslider:{visible:false}},yaxis:{title:`${result.spectrum.unit.includes("mm/s")?"v":"a"} rms [${result.spectrum.unit}]`,range:ref.y_limit,dtick:ref.y_tick,gridcolor:"#dfe7eb",zeroline:false},annotations:annotations.labels||[],shapes:annotations.shapes||[]}; }
  function baseTrace(result) { return {x:result.spectrum.frequencies,y:result.spectrum.amplitudes,type:"scattergl",mode:"lines",name:"Spectrum",line:{color:"#126a82",width:1.2},hovertemplate:"f = %{x:.3f} Hz<br>RMS = %{y:.5g}<extra></extra>"}; }
  function renderPhase1(result) { state.phase1=result; renderMetadata(result); el("workspace").classList.remove("hidden"); Plotly.react("phase1-plot",[baseTrace(result)],plotLayout(result,1),{responsive:true,scrollZoom:true,displaylogo:false,modeBarButtonsToRemove:["lasso2d","select2d"]}); }
  function phase2Traces(result) { const peaks=result.analysis.peaks,matched=peaks.filter(p=>p.match_status),unmatched=peaks.filter(p=>!p.match_status),sidebands=result.analysis.sidebands; const hover=p=>`${p.frequency_hz.toFixed(3)} Hz<br>RMS ${p.amplitude.toPrecision(5)}<br>${p.match_status?`${p.characteristic} · ${p.component}`:"No table match"}`; const trace=(items,name,color,symbol)=>({x:items.map(p=>p.frequency_hz),y:items.map(p=>p.amplitude),type:"scatter",mode:"markers",name,marker:{color,size:8,symbol,line:{color:"white",width:1}},text:items.map(hover),hovertemplate:"%{text}<extra></extra>"}); const sideTrace={x:sidebands.map(p=>p.frequency_hz),y:sidebands.map(p=>p.amplitude),type:"scatter",mode:"markers",name:"Sidebands",marker:{color:"#d97728",size:7,symbol:"circle-open",line:{width:1.5}},text:sidebands.map(p=>`${p.frequency_hz.toFixed(3)} Hz<br>${p.side} sideband · ${p.spacing_name}`),hovertemplate:"%{text}<extra></extra>"}; return [baseTrace(result),trace(matched,"Matched characteristics","#c83e3e","triangle-up"),trace(unmatched,"Unmatched significant peaks","#398b69","diamond"),...(sidebands.length?[sideTrace]:[])]; }
  function phase2Annotations(result) { const peaks=[...result.analysis.peaks].sort((a,b)=>b.amplitude-a.amplitude).slice(0,12); const labels=peaks.map((p,i)=>({x:p.frequency_hz,y:p.amplitude,xref:"x",yref:"y",text:`${p.frequency_hz.toFixed(2)} Hz`,showarrow:true,arrowhead:0,ax:0,ay:i%2?-30:30,font:{size:10,color:p.match_status?"#b23434":"#267350"},bgcolor:"#ffffffdd",bordercolor:p.match_status?"#e8b1b1":"#b8d9c8",borderwidth:1,borderpad:2})); const shapes=result.analysis.peaks.filter(p=>p.match_status).map(p=>({type:"line",x0:p.frequency_hz,x1:p.frequency_hz,y0:0,y1:p.amplitude,line:{color:"#c83e3e",width:1,dash:"dot"}})); return {labels,shapes}; }
  function renderPeakTable(result) { el("peak-table").innerHTML=result.analysis.peaks.map(p=>`<tr><td>${formatNumber(p.frequency_hz,3)}</td><td>${formatNumber(p.amplitude,5)}</td><td class="${p.match_status?"match-yes":"match-no"}">${p.match_status?"Yes":"No"}</td><td>${p.characteristic?`${p.characteristic} · ${p.component}`:"—"}</td><td>${formatNumber(p.difference_hz,3)}</td><td>${p.sidebands.length||"—"}</td></tr>`).join(""); el("peak-table-wrap").classList.remove("hidden"); }
  function renderPhase2(result) { state.phase2=result; el("phase2-section").classList.remove("hidden"); const c=result.analysis.counts; el("analysis-counts").textContent=`${c.detected_peaks} peaks · ${c.matched_peaks} matches · ${c.sideband_hits} sideband hits`; Plotly.react("phase2-plot",phase2Traces(result),plotLayout(result,2,phase2Annotations(result)),{responsive:true,scrollZoom:true,displaylogo:false}); renderPeakTable(result); el("phase2-section").scrollIntoView({behavior:"smooth",block:"start"}); }
  el("upload-form").addEventListener("submit",async e=>{e.preventDefault();if(!state.file||state.busy)return;if(!state.file.name.toLowerCase().endsWith(".uff"))return setMessage("Please choose a file with the .uff extension.","error");setBusy(true,"Processing UFF file and generating the Phase 1 spectrum…");try{renderPhase1(await request("/api/analyze"));setMessage("Phase 1 spectrum ready.","success");}catch(error){console.error(error);setMessage(error.message||"Unable to process the UFF file.","error");}finally{setBusy(false);}});
  el("phase2-button").addEventListener("click",async()=>{if(!state.file||state.busy)return;setBusy(true,el("sideband-analysis").checked?"Running Phase 2 peak and sideband analysis…":"Running Phase 2 peak and characteristic-frequency analysis…");try{renderPhase2(await request("/api/analyze/phase2",el("sideband-analysis").checked));setMessage("Phase 2 analysis ready.","success");}catch(error){console.error(error);setMessage(error.message||"Unable to complete the analysis.","error");}finally{setBusy(false);}});
  if(typeof Plotly==="undefined")setMessage("The interactive plotting library could not be loaded. Check network access and refresh.","error");
})();
